# Site settings
course_code: ELL881/AIL821
course_name: "Large Language Models (LLMs): Introduction and Recent Advances"
course_description: "The field of Natural Language Processing (NLP) has witnessed rapid progress in recent times, driven mainly by the design and development of Large Language Models (LLMs). With the increase in scale, LLMs exhibit various emergent properties, though there are conflicting opinions among researchers about these phenomena. Nonetheless, LLMs are proving to be useful and are becoming ubiquitous across numerous applications.<br/><br/>This advanced course aims to introduce the latest advancements in generative AI for text and is open to both undergraduate and graduate students. The course is structured into five modules: Basics, Architecture, Learnability, User Acceptability, and Ethics & Miscellaneous. Together, these modules will provide a comprehensive view of the different facets of LLMs.<br/><br/>Students should have a background in Machine Learning and be proficient in Python programming. At least some basic knowledge of Deep Learning and NLP is preferred. Through assignments and a course project, students will acquire the skills necessary to design, implement, and understand LLMs using the PyTorch framework."
course_semester: "Semester I, 2024-25"

baseurl: "/ELL881-AIL821-2401" # the subpath of your site, e.g. /blog/
url: "http://lcs2-iitd.github.io/" # the base hostname & protocol for your site

schoolname: "IIT Delhi"
schoolurl: "https://www.lcs2.in"
twitter_username: lcs2lab 

address: |
    Laboratory for Computational Social Systems (LCS2)
    Indian Institute of Technology Delhi
    Hauz Khas, New Delhi - 110016, India

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
